### ISSUE TITLE
Exception handling error upon talking

### ISSUE THREAD

**Issue by ExcaliburZero** [Rui914/mobtalker_old#6]
I just tried using the mobtalker item on a creeper and I got this error.

![screenshot_20150510_123859](https://cloud.githubusercontent.com/assets/4276196/7555211/be3aff04-f711-11e4-8e8d-95d51c05ec3a.png)

**Comment by Rui914** [comment]
It occurs when the exception occurs.
Currently, because the text is not prepared, the error is displayed.
