### ISSUE TITLE
Add information on API

### ISSUE THREAD

**Issue by ExcaliburZero** [Rui914/mobtalker_old#9]
Currently there isn't much information on the API used by the mod. There should be some information provided on the API so that other mods can implement support for it.

It may be a good idea to use [GitHub's wiki feature](https://github.com/Rui914/mobtalker/wiki) for this.

**Comment by ExcaliburZero** [comment]
Taking a look at the creeper mod, it looks like these are the things that have been added to enable mobtalker support.

Above entity registration:
```
if minetest.get_modpath("mobtalker") then
	creeper_talk = {}
	creeper_love = {}
end
```

In `on_rightclick` function:
```
if minetest.get_modpath("mobtalker") and clicker:get_wielded_item():get_name() == "mobtalker:mobtalker"
or minetest.get_modpath("mobtalker") and minetest.setting_getbool("creative_mode") then
	mobtalker_creeper(self,clicker)
end
```

In `on_punch` function:
```
if minetest.get_modpath("mobtalker") then
	if creeper_love[self] > 0 then
		creeper_love[self] = creeper_love[self] - 1
	end
end
```

In `on_step` function:
```
if minetest.get_modpath("mobtalker") then
	if creeper_love[self] == nil then
		creeper_love[self] = 0
	end
	if not creeper_talk[self] then
		creeper_action(self, dtime)
	end
else
	creeper_action(self, dtime)
end
```

**Comment by ExcaliburZero** [comment]
I took a quick look at the API for the Simple Mobs mod, and it looks like there might need to be a few changes made in order to incorporate modtalker.

**Comment by Rui914** [comment]
This Mod is still in beta.
Therefore, will frequently API is changed.
Don't edit the Wiki until this Mod reaches 0.1.

**Comment by Rui914** [comment]
I have added a variety of API.
But, I not good at English.
if you care, can you write on my behalf?

**Comment by ExcaliburZero** [comment]
@Rui914 
Sure. I'll look over the code and come up with some documentation for the API.

I've added some documentation for [`mobtalker_setstatic()`](https://github.com/Rui914/mobtalker/wiki#mobtalker_setstaticselfstaticdata). Let me know if that is sufficient or if I should add some more information on it.

**Comment by ExcaliburZero** [comment]
I have also added some documentation on the [`xform()`](https://github.com/Rui914/mobtalker/wiki#xformmobnametextdef) function.

**Comment by ExcaliburZero** [comment]
Also a link to the wiki with the API should probably be added to the README file and the forum topic.

**Comment by ExcaliburZero** [comment]
I added some documentation on the `mobtalker.register_name()` and `mobtalker.punch()` functions.

I also created a table of contents that lists the functions and links to their section on the wiki, as that should make it a bit easier to see what all of the functions are.

**Comment by ExcaliburZero** [comment]
I added some documentation on the `mobtalker.savestatic()` function.

**Comment by ExcaliburZero** [comment]
I added some documentation on the `mobtalker.rightclick()` function.

Let me know if there is anything else you would like me to add information on to the wiki.

**Comment by Rui914** [comment]
https://github.com/Rui914/mobtalker_modpack/wiki
